### ISSUE TITLE
Support for W25Q128JVS flash chip

### ISSUE THREAD

**Issue by renzenicolai** [rhulme/pico-flashloader#1]
Awesome project! I'd love to use this flashloader in my project, but while it works on the Pico it fails to boot the application on a board that is implemented according to the minimal design presented in https://datasheets.raspberrypi.com/rp2040/hardware-design-with-rp2040.pdf , that design uses a W25Q128JVS flash chip.

**Comment by rhulme** [comment]
Does the 'blink' example from pico-examples work without modification on your board?  I don't know whether the standard 2nd level bootloader is compatible with the W25Q128JVS chip.  If not, that would probably explain what you're seeing.

I've used pico-flashloader myself on a board that required the basic int03 bootloader and it worked fine.  It doesn't fiddle with any QSPI settings so as long as the correct 2nd level bootloader is being used, it *should* work fine.

**Comment by rhulme** [comment]
I'm going to close this due to lack of information.  If it is still a problem, please open a new issue.
